const MAX_NUMBERS_OF_DAYS = 31
const MAX_NUMBERS_OF_MONTHS = 12

const CURRENT_DATE = new Date()

const QUESTIONS = {
    day: 'Введите день Вашего рождения ->',
    month: 'Введите месяц Вашего рождения ->',
    year: 'Введите год Вашего рождения ->',
}

const CONSOLE_NUMBERS = {
    separator: ['  ',
                '  ',
                '  ', 
                '  ', 
                '  ', 
                '  ', 
                '  ', 
                '  ', 
                '  '],
    0: [' **** ',
        '**  **', 
        '**  **', 
        '**  **',  
        '**  **', 
        '**  **', 
        '**  **',  
        '**  **', 
        ' **** '],
    1: [' ***', 
        '****', 
        '  **', 
        '  **', 
        '  **', 
        '  **', 
        '  **', 
        '  **', 
        '  **'],
    2: ['****  ', 
        '**  **', 
        '    **', 
        '    **', 
        '   ** ', 
        '  **  ', 
        ' **   ', 
        '**    ', 
        '******'],
    3: [' **** ',
        '**  **',
        '    **',
        '    **',
        '  *** ',
        '    **',
        '    **',
        '**  **',
        ' **** '],
    4: ['   ** ',
        '  *** ',
        '  *** ',
        ' **** ',
        ' * ** ',
        '** ** ',
        '******',
        '   ** ',
        '   ** '],
    5: ['******',
        '**    ',
        '**    ',
        '***** ',
        '**  **',
        '    **',
        '    **',
        '**  **',
        ' **** '],
    6: [' **** ',
        '**  **',
        '**    ',
        '**    ',
        '***** ',
        '**  **',
        '**  **',
        '**  **',
        ' **** '],
    7: ['******',
        '    **',
        '   ** ',
        '   ** ',
        '  **  ',
        '  **  ',
        ' **   ',
        ' **   ',
        ' **   '],
    8: [' **** ',
        '**  **',
        '**  **',
        '**  **',
        ' **** ',
        '**  **',
        '**  **',
        '**  **',
        ' **** '],
    9: [' **** ',
        '**  **',
        '**  **',
        '**  **',
        ' *****',
        '    **',
        '    **',
        '**  **',
        ' **** '],
}

const VALIDATION_ERROR_MESSAGE = 'Дата введена некорректно. (╯°□°）╯︵ ┻━┻ '
const DATE_FROM_THE_FUTURE_ERROR_MESSAGE = 'Введите, пожалуйста, коррекную дату (не из будущего)'

module.exports.QUESTIONS = QUESTIONS
module.exports.MAX_NUMBERS_OF_DAYS = MAX_NUMBERS_OF_DAYS
module.exports.MAX_NUMBERS_OF_MONTHS = MAX_NUMBERS_OF_MONTHS
module.exports.CONSOLE_NUMBERS = CONSOLE_NUMBERS
module.exports.VALIDATION_ERROR_MESSAGE = VALIDATION_ERROR_MESSAGE
module.exports.DATE_FROM_THE_FUTURE_ERROR_MESSAGE = DATE_FROM_THE_FUTURE_ERROR_MESSAGE
module.exports.CURRENT_DATE = CURRENT_DATE
